app:
  build: ./app # EXPOSEs 80
  dockerfile: Dockerfile-prod
  restart: always
  environment:
   - VERSION=${VERSION}
   - ROOT_URL=https://signmeup.cs.cornell.edu
   - MONGO_URL=mongodb://db:27017/signmeup
   - VIRTUAL_HOST=signmeup.cs.cornell.edu
   - METEOR_SETTINGS=${METEOR_SETTINGS}
   - MAIL_URL=smtp://mail.cs.cornell.edu:25
   - HTTP_FORWARDED_COUNT=1
   - PRODUCTION=true

db:
  restart: always
  volumes:
   - ./mongodb/data:/data/db

proxy:
  restart: always
  ports:
   - 80:80
   - 443:443
